language: go

go:
  - tip

addons:
  postgresql: "9.3"

services:
  - mongodb

before_install:
  - sudo apt-get install -y bzr

install:
  - go get github.com/lib/pq
  - go get github.com/kellydunn/golang-geo
  - go get github.com/kpawlik/geojson
  - go get gopkg.in/mgo.v2

before_script:
  - psql -c 'create database travis_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_postgis
